# Generated by Django 2.0 on 2020-02-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Brief',
            new_name='brief',
        ),
    ]
